### ISSUE TITLE
TeX Live 2021中不兼容interfaces包

### ISSUE THREAD

**Issue by xiehao** [htharoldht/USTBExam#1]
在`overleaf`上导入该工程、并选择TeX Live 2021版本编译时报错（2019版本没问题），但可以正常生成pdf。

原因应该是在生成试卷头的表格时用到了`interfaces-makecell`这个包，该包在2021版本中不兼容，请问有什么替代方案么？谢谢！

**Comment by htharoldht** [comment]
不好意思，才看到issue

在今年四月份的那次commit的时候已经修复了这个问题
